# Done to increase the memory available to gradle.
	org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	minecraft_version=26.1.2
	loader_version=0.19.3
 	fabric_version=0.155.2+26.1.2

# Mod Properties
	mod_version = 1.5.1
	maven_group = dev.ztereohype
	archives_base_name = nicer-skies

# Mod Dependencies
	modmenu_version = 18.0.0

# Other Dependencies
	lombok_version = 1.18.40
	junit_version = 5.10.3
